name: my_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  custom_radio_grouped_button: ^2.1.2+2
  get: 4.6.5
  get_cli: ^1.8.1
  google_fonts: ^3.0.1
  group_button: ^5.0.1
  firebase_auth: 3.6.2
  cloud_firestore: 3.4.3
  firebase_core: 1.20.0
  google_sign_in: 5.4.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

